### ISSUE TITLE
Change color theme of the website

### ISSUE THREAD

**Issue by kaushal3103** [kaushal3103/Movie-and-TVshow-database#1]
You have to change the color theme of the website. I prefer light themes. Use your imagination and creativity.

**Comment by apelnar0517** [comment]
I'd like to take a shot at this if no one's started. Can you assign this to me?

**Comment by MaitriDA** [comment]
Can you assign me this issue.

**Comment by kaushal3103** [comment]
@apelnar0517 you can start with task !

**Comment by kaushal3103** [comment]
@apelnar0517 Sorry previously I failed to upload the package JSON files. But now I have uploaded you can start with your task now !

**Comment by kaushal3103** [comment]
@MaitriDA you can start with task !

**Comment by kaushal3103** [comment]
@apelnar0517 @MaitriDA if you guys facing INVALID API KEY issue you can request your own api key from https://www.themoviedb.org/
or you can request me i will send you mine for this purpose
