### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by kaushal3103** [kaushal3103/Movie-and-TVshow-database#2]
In this readme file you have to make it more attractive like you can add some descriptions and some screenshots

**Comment by sugato1398** [comment]
hi, im interested to work on this issue, i tried to run the app locally but im experiencing "Invalid API key: You must be granted a valid key." issue when the network calls happen, is there a solution for this

**Comment by kaushal3103** [comment]
@sugato1398 well thank you ! I did not wanted to share API key because of privacy purposes. you can request the API key from https://www.themoviedb.org/ or if you want I can share you mine API KEY

**Comment by sugato1398** [comment]
hi, thanks for assigning the issue, can you provide me the key, or share
the .env file
.

Regards,
Sugato

**Comment by kaushal3103** [comment]
@sugato1398 Okay I'm providing you mine API key. Create .env file and paste REACT_APP_API_KEY= afab452e4c8f150a284c17d981111e3b
Thanks
